openapi: 3.2.0
info:
  title: Enterprise Search Document API
  version: 0.1.0
tags:
- name: Document
paths:
  /v01/document/transcribe_documents:
    post:
      tags:
      - Document
      summary: Document Transcription Endpoint
      description: Lambda function to transcribe documents using OCR and return the text
      operationId: document_transcription_endpoint_v01_document_transcribe_documents_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JsonRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    JsonRequest:
      properties: {}
      additionalProperties: true
      type: object
      title: JsonRequest
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
